const skipKeys = new Set([
  'slug',
  'path',
  'canonicalPath',
  'imagePath',
  'imageUrl',
  'logoPath',
  'siteUrl',
  'url',
  'sameAs',
  'publishedTime',
  'modifiedTime',
  'categorySlug',
  'keywords'
]);

const replacements: Array<[string, string]> = [
  ['O Que E', 'O Que É'],
  ['O Que e', 'O Que é'],
  ['O que E', 'O que É'],
  ['O Que Sao', 'O Que São'],
  ['O que sao', 'O que são'],
  ['Como E', 'Como É'],
  ['Qual e', 'Qual é'],
  ['O que e', 'O que é'],
  ['O objetivo e', 'O objetivo é'],
  ['o objetivo e', 'o objetivo é'],
  ['A funcao da pagina e', 'A função da página é'],
  ['a funcao da pagina e', 'a função da página é'],
  ['O foco aqui e', 'O foco aqui é'],
  ['o foco aqui e', 'o foco aqui é'],
  ['O objetivo da ferramenta e', 'O objetivo da ferramenta é'],
  ['o objetivo da ferramenta e', 'o objetivo da ferramenta é'],
  ['Nao esta', 'Não está'],
  ['nao esta', 'não está'],
  ['Ja esta', 'Já está'],
  ['ja esta', 'já está'],
  ['Quando ainda nao esta claro', 'Quando ainda não está claro'],
  ['quando ainda nao esta claro', 'quando ainda não está claro'],
  ['A direcao da arquitetura e', 'A direção da arquitetura é'],
  ['a direcao da arquitetura e', 'a direção da arquitetura é'],
  ['Cada ferramenta ganha pagina propria', 'Cada ferramenta ganha página própria'],
  ['cada ferramenta ganha pagina propria', 'cada ferramenta ganha página própria'],
  ['Esta base publica', 'Esta base pública'],
  ['esta base publica', 'esta base pública'],
  ['estrutura publica', 'estrutura pública'],
  ['base publica', 'base pública'],
  ['melhor proximo passo e', 'melhor próximo passo é'],
  ['governanca continua', 'governança contínua'],
  ['acompanhamento continuo', 'acompanhamento contínuo'],
  ['direcao continua', 'direção contínua'],
  ['AGENCIA', 'AGÊNCIA'],
  ['ANCORA', 'ÂNCORA'],
  ['ATENCAO', 'ATENÇÃO'],
  ['CAPTACAO', 'CAPTAÇÃO'],
  ['CANONICO', 'CANÔNICO'],
  ['CANONICOS', 'CANÔNICOS'],
  ['CLINICAS', 'CLÍNICAS'],
  ['COMUNICACAO', 'COMUNICAÇÃO'],
  ['CONTRATACAO', 'CONTRATAÇÃO'],
  ['DECISAO', 'DECISÃO'],
  ['DIFERENCA', 'DIFERENÇA'],
  ['DIRECAO', 'DIREÇÃO'],
  ['ENDERECO', 'ENDEREÇO'],
  ['ESPECIALIZACAO', 'ESPECIALIZAÇÃO'],
  ['EXECUCAO', 'EXECUÇÃO'],
  ['FUNCAO', 'FUNÇÃO'],
  ['GENERICA', 'GENÉRICA'],
  ['GEOGRAFICO', 'GEOGRÁFICO'],
  ['LIGACAO', 'LIGAÇÃO'],
  ['INDICE', 'ÍNDICE'],
  ['INFORMACOES', 'INFORMAÇÕES'],
  ['INSCRICAO', 'INSCRIÇÃO'],
  ['INTERACAO', 'INTERAÇÃO'],
  ['LICITO', 'LÍCITO'],
  ['MEDICAS', 'MÉDICAS'],
  ['METODO', 'MÉTODO'],
  ['METODOS', 'MÉTODOS'],
  ['MINIMO', 'MÍNIMO'],
  ['NEGOCIO', 'NEGÓCIO'],
  ['NEGOCIOS', 'NEGÓCIOS'],
  ['OBRIGACAO', 'OBRIGAÇÃO'],
  ['OBRIGACOES', 'OBRIGAÇÕES'],
  ['PADRAO', 'PADRÃO'],
  ['PADROES', 'PADRÕES'],
  ['POLITICA', 'POLÍTICA'],
  ['PREVENCAO', 'PREVENÇÃO'],
  ['PRIORIZACAO', 'PRIORIZAÇÃO'],
  ['PROPRIAS', 'PRÓPRIAS'],
  ['PROPRIOS', 'PRÓPRIOS'],
  ['PROTECAO', 'PROTEÇÃO'],
  ['PROPRIA', 'PRÓPRIA'],
  ['PROPRIO', 'PRÓPRIO'],
  ['PROXIMO', 'PRÓXIMO'],
  ['PUBLICA', 'PÚBLICA'],
  ['PUBLICAS', 'PÚBLICAS'],
  ['PUBLICITARIA', 'PUBLICITÁRIA'],
  ['PUBLICO', 'PÚBLICO'],
  ['PUBLICOS', 'PÚBLICOS'],
  ['REFORCO', 'REFORÇO'],
  ['REFORCAR', 'REFORÇAR'],
  ['REGULATORIA', 'REGULATÓRIA'],
  ['REGULATORIAS', 'REGULATÓRIAS'],
  ['REGULATORIO', 'REGULATÓRIO'],
  ['RETENCAO', 'RETENÇÃO'],
  ['REVISAO', 'REVISÃO'],
  ['SEGURANCA', 'SEGURANÇA'],
  ['SESSAO', 'SESSÃO'],
  ['SOLICITACAO', 'SOLICITAÇÃO'],
  ['TECNICAS', 'TÉCNICAS'],
  ['TECNICOS', 'TÉCNICOS'],
  ['TRANSPARENCIA', 'TRANSPARÊNCIA'],
  ['USUARIO', 'USUÁRIO'],
  ['USUARIOS', 'USUÁRIOS'],
  ['VALIDACAO', 'VALIDAÇÃO'],
  ['VISAO', 'VISÃO'],
  ['VARIACOES', 'VARIAÇÕES'],
  ['VARIAS', 'VÁRIAS'],
  ['AGENCIA', 'AGÊNCIA'],
  ['PAGINA', 'PÁGINA'],
  ['PAGINAS', 'PÁGINAS'],
  ['SERVICOS', 'SERVIÇOS'],
  ['DIAGNOSTICO', 'DIAGNÓSTICO'],
  ['OPERACAO', 'OPERAÇÃO'],
  ['OPERACOES', 'OPERAÇÕES'],
  ['CONTEUDO', 'CONTEÚDO'],
  ['CONTEUDOS', 'CONTEÚDOS'],
  ['CONVERSAO', 'CONVERSÃO'],
  ['DISTRIBUICAO', 'DISTRIBUIÇÃO'],
  ['MEDICAO', 'MEDIÇÃO'],
  ['ITERACAO', 'ITERAÇÃO'],
  ['REUNIOES', 'REUNIÕES'],
  ['SEMANTICA', 'SEMÂNTICA'],
  ['GOVERNANCA', 'GOVERNANÇA'],
  ['LOCALIZACAO', 'LOCALIZAÇÃO'],
  ['REGIAO', 'REGIÃO'],
  ['ANALISE', 'ANÁLISE'],
  ['CONFIANCA', 'CONFIANÇA'],
  ['EXPERIENCIA', 'EXPERIÊNCIA'],
  ['OTIMIZACAO', 'OTIMIZAÇÃO'],
  ['IMPLEMENTACAO', 'IMPLEMENTAÇÃO'],
  ['APLICACAO', 'APLICAÇÃO'],
  ['OBJECAO', 'OBJEÇÃO'],
  ['CITACAO', 'CITAÇÃO'],
  ['RELACAO', 'RELAÇÃO'],
  ['COMPARACAO', 'COMPARAÇÃO'],
  ['ESPACO', 'ESPAÇO'],
  ['UNICO', 'ÚNICO'],
  ['SAO', 'SÃO'],
  ['NAO', 'NÃO'],
  ['Alem', 'Além'],
  ['alem', 'além'],
  ['Avaliacao', 'Avaliação'],
  ['avaliacao', 'avaliação'],
  ['Agencia', 'Agência'],
  ['Ancora', 'Âncora'],
  ['ancora', 'âncora'],
  ['Atencao', 'Atenção'],
  ['atencao', 'atenção'],
  ['Atuacao', 'Atuação'],
  ['atuacao', 'atuação'],
  ['Acumulacao', 'Acumulação'],
  ['acumulacao', 'acumulação'],
  ['Aquisicao', 'Aquisição'],
  ['aquisicao', 'aquisição'],
  ['Aquisicoes', 'Aquisições'],
  ['aquisicoes', 'aquisições'],
  ['Atribuido', 'Atribuído'],
  ['atribuido', 'atribuído'],
  ['Atribuida', 'Atribuída'],
  ['atribuida', 'atribuída'],
  ['Atribuidos', 'Atribuídos'],
  ['atribuidos', 'atribuídos'],
  ['Atribuidas', 'Atribuídas'],
  ['atribuidas', 'atribuídas'],
  ['Canonico', 'Canônico'],
  ['canonico', 'canônico'],
  ['Canonicos', 'Canônicos'],
  ['canonicos', 'canônicos'],
  ['Captacao', 'Captação'],
  ['captacao', 'captação'],
  ['Clinicas', 'Clínicas'],
  ['clinicas', 'clínicas'],
  ['Comunicacao', 'Comunicação'],
  ['comunicacao', 'comunicação'],
  ['Contratacao', 'Contratação'],
  ['contratacao', 'contratação'],
  ['Decisao', 'Decisão'],
  ['decisao', 'decisão'],
  ['Diferenca', 'Diferença'],
  ['diferenca', 'diferença'],
  ['Direcao', 'Direção'],
  ['direcao', 'direção'],
  ['Endereco', 'Endereço'],
  ['endereco', 'endereço'],
  ['Especializacao', 'Especialização'],
  ['especializacao', 'especialização'],
  ['Execucao', 'Execução'],
  ['execucao', 'execução'],
  ['Escritorios', 'Escritórios'],
  ['escritorios', 'escritórios'],
  ['Funcao', 'Função'],
  ['funcao', 'função'],
  ['Generica', 'Genérica'],
  ['generica', 'genérica'],
  ['Generico', 'Genérico'],
  ['generico', 'genérico'],
  ['Genericos', 'Genéricos'],
  ['genericos', 'genéricos'],
  ['Genericas', 'Genéricas'],
  ['genericas', 'genéricas'],
  ['Geografico', 'Geográfico'],
  ['geografico', 'geográfico'],
  ['Historico', 'Histórico'],
  ['historico', 'histórico'],
  ['Intervencao', 'Intervenção'],
  ['intervencao', 'intervenção'],
  ['Intervencoes', 'Intervenções'],
  ['intervencoes', 'intervenções'],
  ['Indice', 'Índice'],
  ['indice', 'índice'],
  ['Informacao', 'Informação'],
  ['informacao', 'informação'],
  ['Informacoes', 'Informações'],
  ['informacoes', 'informações'],
  ['Integracao', 'Integração'],
  ['integracao', 'integração'],
  ['Integracoes', 'Integrações'],
  ['integracoes', 'integrações'],
  ['Inscricao', 'Inscrição'],
  ['inscricao', 'inscrição'],
  ['Interacao', 'Interação'],
  ['interacao', 'interação'],
  ['Licito', 'Lícito'],
  ['licito', 'lícito'],
  ['Ligacao', 'Ligação'],
  ['ligacao', 'ligação'],
  ['Medicas', 'Médicas'],
  ['medicas', 'médicas'],
  ['Metodo', 'Método'],
  ['metodo', 'método'],
  ['Observacao', 'Observação'],
  ['observacao', 'observação'],
  ['Observacoes', 'Observações'],
  ['observacoes', 'observações'],
  ['agencia', 'agência'],
  ['Minimo', 'Mínimo'],
  ['minimo', 'mínimo'],
  ['Minimos', 'Mínimos'],
  ['minimos', 'mínimos'],
  ['Navegacao', 'Navegação'],
  ['navegacao', 'navegação'],
  ['Negocio', 'Negócio'],
  ['negocio', 'negócio'],
  ['Negocios', 'Negócios'],
  ['negocios', 'negócios'],
  ['Obrigacao', 'Obrigação'],
  ['obrigacao', 'obrigação'],
  ['Obrigacoes', 'Obrigações'],
  ['obrigacoes', 'obrigações'],
  ['Pagina', 'Página'],
  ['pagina', 'página'],
  ['Paginas', 'Páginas'],
  ['paginas', 'páginas'],
  ['Padrao', 'Padrão'],
  ['padrao', 'padrão'],
  ['Padroes', 'Padrões'],
  ['padroes', 'padrões'],
  ['Politica', 'Política'],
  ['politica', 'política'],
  ['Preferencia', 'Preferência'],
  ['preferencia', 'preferência'],
  ['Prevencao', 'Prevenção'],
  ['prevencao', 'prevenção'],
  ['Primaria', 'Primária'],
  ['primaria', 'primária'],
  ['Servicos', 'Serviços'],
  ['servicos', 'serviços'],
  ['Servico', 'Serviço'],
  ['servico', 'serviço'],
  ['Diagnostico', 'Diagnóstico'],
  ['diagnostico', 'diagnóstico'],
  ['Operacao', 'Operação'],
  ['operacao', 'operação'],
  ['Operacoes', 'Operações'],
  ['operacoes', 'operações'],
  ['Conteudo', 'Conteúdo'],
  ['conteudo', 'conteúdo'],
  ['Conteudos', 'Conteúdos'],
  ['conteudos', 'conteúdos'],
  ['Conversao', 'Conversão'],
  ['conversao', 'conversão'],
  ['Distribuicao', 'Distribuição'],
  ['distribuicao', 'distribuição'],
  ['Medicao', 'Medição'],
  ['medicao', 'medição'],
  ['Formulario', 'Formulário'],
  ['formulario', 'formulário'],
  ['Formularios', 'Formulários'],
  ['formularios', 'formulários'],
  ['Iteracao', 'Iteração'],
  ['iteracao', 'iteração'],
  ['Reunioes', 'Reuniões'],
  ['reunioes', 'reuniões'],
  ['Reuniao', 'Reunião'],
  ['reuniao', 'reunião'],
  ['Semantica', 'Semântica'],
  ['semantica', 'semântica'],
  ['Governanca', 'Governança'],
  ['governanca', 'governança'],
  ['Priorizacao', 'Priorização'],
  ['priorizacao', 'priorização'],
  ['Proprias', 'Próprias'],
  ['proprias', 'próprias'],
  ['Proprios', 'Próprios'],
  ['proprios', 'próprios'],
  ['Protecao', 'Proteção'],
  ['protecao', 'proteção'],
  ['Propria', 'Própria'],
  ['propria', 'própria'],
  ['Proprio', 'Próprio'],
  ['proprio', 'próprio'],
  ['Proximo', 'Próximo'],
  ['proximo', 'próximo'],
  ['Publicas', 'Públicas'],
  ['publicas', 'públicas'],
  ['Publicitaria', 'Publicitária'],
  ['publicitaria', 'publicitária'],
  ['Publico', 'Público'],
  ['publico', 'público'],
  ['Publicos', 'Públicos'],
  ['publicos', 'públicos'],
  ['Reforco', 'Reforço'],
  ['reforco', 'reforço'],
  ['Reforcar', 'Reforçar'],
  ['reforcar', 'reforçar'],
  ['Regulatoria', 'Regulatória'],
  ['regulatoria', 'regulatória'],
  ['Regulatorias', 'Regulatórias'],
  ['regulatorias', 'regulatórias'],
  ['Regulatorio', 'Regulatório'],
  ['regulatorio', 'regulatório'],
  ['Retencao', 'Retenção'],
  ['retencao', 'retenção'],
  ['Revisao', 'Revisão'],
  ['revisao', 'revisão'],
  ['Seguranca', 'Segurança'],
  ['seguranca', 'segurança'],
  ['Sessao', 'Sessão'],
  ['sessao', 'sessão'],
  ['Solicitacao', 'Solicitação'],
  ['solicitacao', 'solicitação'],
  ['Localizacao', 'Localização'],
  ['localizacao', 'localização'],
  ['Regiao', 'Região'],
  ['regiao', 'região'],
  ['Recomendacao', 'Recomendação'],
  ['recomendacao', 'recomendação'],
  ['Recomendacoes', 'Recomendações'],
  ['recomendacoes', 'recomendações'],
  ['Recuperaveis', 'Recuperáveis'],
  ['recuperaveis', 'recuperáveis'],
  ['Referencia', 'Referência'],
  ['referencia', 'referência'],
  ['Referencias', 'Referências'],
  ['referencias', 'referências'],
  ['Reputacao', 'Reputação'],
  ['reputacao', 'reputação'],
  ['Analise', 'Análise'],
  ['analise', 'análise'],
  ['Responsavel', 'Responsável'],
  ['responsavel', 'responsável'],
  ['Confianca', 'Confiança'],
  ['confianca', 'confiança'],
  ['Conexao', 'Conexão'],
  ['conexao', 'conexão'],
  ['Consolidacao', 'Consolidação'],
  ['consolidacao', 'consolidação'],
  ['Consistencia', 'Consistência'],
  ['consistencia', 'consistência'],
  ['Concorrencia', 'Concorrência'],
  ['concorrencia', 'concorrência'],
  ['Criterio', 'Critério'],
  ['criterio', 'critério'],
  ['Criterios', 'Critérios'],
  ['criterios', 'critérios'],
  ['Dependencia', 'Dependência'],
  ['dependencia', 'dependência'],
  ['Definicao', 'Definição'],
  ['definicao', 'definição'],
  ['Definicoes', 'Definições'],
  ['definicoes', 'definições'],
  ['Documentacao', 'Documentação'],
  ['documentacao', 'documentação'],
  ['Experiencia', 'Experiência'],
  ['experiencia', 'experiência'],
  ['Fundacao', 'Fundação'],
  ['fundacao', 'fundação'],
  ['Otimizacao', 'Otimização'],
  ['otimizacao', 'otimização'],
  ['Implementacao', 'Implementação'],
  ['implementacao', 'implementação'],
  ['Aplicacao', 'Aplicação'],
  ['aplicacao', 'aplicação'],
  ['Objecao', 'Objeção'],
  ['objecao', 'objeção'],
  ['Citacao', 'Citação'],
  ['citacao', 'citação'],
  ['Comeca', 'Começa'],
  ['comeca', 'começa'],
  ['Comecam', 'Começam'],
  ['comecam', 'começam'],
  ['Comecar', 'Começar'],
  ['comecar', 'começar'],
  ['Construcao', 'Construção'],
  ['construcao', 'construção'],
  ['Constroi', 'Constrói'],
  ['constroi', 'constrói'],
  ['Relacao', 'Relação'],
  ['relacao', 'relação'],
  ['Coerencia', 'Coerência'],
  ['coerencia', 'coerência'],
  ['Comparacao', 'Comparação'],
  ['comparacao', 'comparação'],
  ['Comparacoes', 'Comparações'],
  ['comparacoes', 'comparações'],
  ['Espaco', 'Espaço'],
  ['espaco', 'espaço'],
  ['Unico', 'Único'],
  ['unico', 'único'],
  ['Presenca', 'Presença'],
  ['presenca', 'presença'],
  ['Aparicao', 'Aparição'],
  ['aparicao', 'aparição'],
  ['Compreensivel', 'Compreensível'],
  ['compreensivel', 'compreensível'],
  ['Precisao', 'Precisão'],
  ['precisao', 'precisão'],
  ['Atualizacao', 'Atualização'],
  ['atualizacao', 'atualização'],
  ['Atualizacoes', 'Atualizações'],
  ['atualizacoes', 'atualizações'],
  ['Cenario', 'Cenário'],
  ['cenario', 'cenário'],
  ['Intencao', 'Intenção'],
  ['intencao', 'intenção'],
  ['Relevancia', 'Relevância'],
  ['relevancia', 'relevância'],
  ['Sustentacao', 'Sustentação'],
  ['sustentacao', 'sustentação'],
  ['Redacao', 'Redação'],
  ['redacao', 'redação'],
  ['Correcoes', 'Correções'],
  ['correcoes', 'correções'],
  ['Versao', 'Versão'],
  ['versao', 'versão'],
  ['Opiniao', 'Opinião'],
  ['opiniao', 'opinião'],
  ['Producao', 'Produção'],
  ['producao', 'produção'],
  ['Basico', 'Básico'],
  ['basico', 'básico'],
  ['Basicos', 'Básicos'],
  ['basicos', 'básicos'],
  ['Facil', 'Fácil'],
  ['facil', 'fácil'],
  ['Saida', 'Saída'],
  ['saida', 'saída'],
  ['Insercao', 'Inserção'],
  ['insercao', 'inserção'],
  ['Virgulas', 'Vírgulas'],
  ['virgulas', 'vírgulas'],
  ['Invalida', 'Inválida'],
  ['invalida', 'inválida'],
  ['Invalido', 'Inválido'],
  ['invalido', 'inválido'],
  ['Visivel', 'Visível'],
  ['visivel', 'visível'],
  ['Util', 'Útil'],
  ['util', 'útil'],
  ['Legivel', 'Legível'],
  ['legivel', 'legível'],
  ['Especifico', 'Específico'],
  ['especifico', 'específico'],
  ['Especifica', 'Específica'],
  ['especifica', 'específica'],
  ['Propriedade', 'Propriedade'],
  ['propriedade', 'propriedade'],
  ['Qualificacao', 'Qualificação'],
  ['qualificacao', 'qualificação'],
  ['Qualificar', 'Qualificar'],
  ['aprovacao', 'aprovação'],
  ['Aprovacao', 'Aprovação'],
  ['Publicacao', 'Publicação'],
  ['publicacao', 'publicação'],
  ['Publicacoes', 'Publicações'],
  ['publicacoes', 'publicações'],
  ['Conclusao', 'Conclusão'],
  ['conclusao', 'conclusão'],
  ['Conversoes', 'Conversões'],
  ['conversoes', 'conversões'],
  ['Correcao', 'Correção'],
  ['correcao', 'correção'],
  ['Critica', 'Crítica'],
  ['critica', 'crítica'],
  ['Criticas', 'Críticas'],
  ['criticas', 'críticas'],
  ['Critico', 'Crítico'],
  ['critico', 'crítico'],
  ['Criticos', 'Críticos'],
  ['criticos', 'críticos'],
  ['Ate', 'Até'],
  ['ate', 'até'],
  ['Avanca', 'Avança'],
  ['avanca', 'avança'],
  ['Possivel', 'Possível'],
  ['possivel', 'possível'],
  ['Rapida', 'Rápida'],
  ['rapida', 'rápida'],
  ['Rapidas', 'Rápidas'],
  ['rapidas', 'rápidas'],
  ['Validas', 'Válidas'],
  ['validas', 'válidas'],
  ['Validar', 'Validar'],
  ['validar', 'validar'],
  ['Incompativel', 'Incompatível'],
  ['incompativel', 'incompatível'],
  ['Arvore', 'Árvore'],
  ['arvore', 'árvore'],
  ['Superficie', 'Superfície'],
  ['superficie', 'superfície'],
  ['Superficies', 'Superfícies'],
  ['superficies', 'superfícies'],
  ['Ruido', 'Ruído'],
  ['ruido', 'ruído'],
  ['Decisoes', 'Decisões'],
  ['decisoes', 'decisões'],
  ['Defensavel', 'Defensável'],
  ['defensavel', 'defensável'],
  ['Estao', 'Estão'],
  ['estao', 'estão'],
  ['Estrategias', 'Estratégias'],
  ['estrategias', 'estratégias'],
  ['Etico', 'Ético'],
  ['etico', 'ético'],
  ['Etica', 'Ética'],
  ['etica', 'ética'],
  ['Experiencias', 'Experiências'],
  ['experiencias', 'experiências'],
  ['Forca', 'Força'],
  ['forca', 'força'],
  ['Geracao', 'Geração'],
  ['geracao', 'geração'],
  ['Inicio', 'Início'],
  ['inicio', 'início'],
  ['Ligacoes', 'Ligações'],
  ['ligacoes', 'ligações'],
  ['Mes', 'Mês'],
  ['mes', 'mês'],
  ['Minima', 'Mínima'],
  ['minima', 'mínima'],
  ['Minimas', 'Mínimas'],
  ['minimas', 'mínimas'],
  ['Proximos', 'Próximos'],
  ['proximos', 'próximos'],
  ['Proximas', 'Próximas'],
  ['proximas', 'próximas'],
  ['Reforcada', 'Reforçada'],
  ['reforcada', 'reforçada'],
  ['Reforcadas', 'Reforçadas'],
  ['reforcadas', 'reforçadas'],
  ['Reforcado', 'Reforçado'],
  ['reforcado', 'reforçado'],
  ['Reforcados', 'Reforçados'],
  ['reforcados', 'reforçados'],
  ['Reforcando', 'Reforçando'],
  ['reforcando', 'reforçando'],
  ['Calendario', 'Calendário'],
  ['calendario', 'calendário'],
  ['Reorganizacao', 'Reorganização'],
  ['reorganizacao', 'reorganização'],
  ['Serio', 'Sério'],
  ['serio', 'sério'],
  ['Seria', 'Séria'],
  ['seria', 'séria'],
  ['So', 'Só'],
  ['so', 'só'],
  ['Sustentavel', 'Sustentável'],
  ['sustentavel', 'sustentável'],
  ['Tambem', 'Também'],
  ['tambem', 'também'],
  ['Tecnico', 'Técnico'],
  ['tecnico', 'técnico'],
  ['Tecnicos', 'Técnicos'],
  ['tecnicos', 'técnicos'],
  ['Tecnica', 'Técnica'],
  ['tecnica', 'técnica'],
  ['Tecnicas', 'Técnicas'],
  ['tecnicas', 'técnicas'],
  ['Transparencia', 'Transparência'],
  ['transparencia', 'transparência'],
  ['Usuario', 'Usuário'],
  ['usuario', 'usuário'],
  ['Usuarios', 'Usuários'],
  ['usuarios', 'usuários'],
  ['Validacao', 'Validação'],
  ['validacao', 'validação'],
  ['Voce', 'Você'],
  ['voce', 'você'],
  ['Estrategia', 'Estratégia'],
  ['estrategia', 'estratégia'],
  ['Estrategico', 'Estratégico'],
  ['estrategico', 'estratégico'],
  ['Estrategica', 'Estratégica'],
  ['estrategica', 'estratégica'],
  ['Organico', 'Orgânico'],
  ['organico', 'orgânico'],
  ['Citavel', 'Citável'],
  ['citavel', 'citável'],
  ['Necessario', 'Necessário'],
  ['necessario', 'necessário'],
  ['Rapido', 'Rápido'],
  ['rapido', 'rápido'],
  ['Duvidas', 'Dúvidas'],
  ['duvidas', 'dúvidas'],
  ['Metodos', 'Métodos'],
  ['metodos', 'métodos'],
  ['Sinonimo', 'Sinônimo'],
  ['sinonimo', 'sinônimo'],
  ['Sinonimos', 'Sinônimos'],
  ['sinonimos', 'sinônimos'],
  ['Sensivel', 'Sensível'],
  ['sensivel', 'sensível'],
  ['Sensiveis', 'Sensíveis'],
  ['sensiveis', 'sensíveis'],
  ['Praca', 'Praça'],
  ['praca', 'praça'],
  ['Pracas', 'Praças'],
  ['pracas', 'praças'],
  ['Pratico', 'Prático'],
  ['pratico', 'prático'],
  ['Pratica', 'Prática'],
  ['pratica', 'prática'],
  ['Praticos', 'Práticos'],
  ['praticos', 'práticos'],
  ['Praticas', 'Práticas'],
  ['praticas', 'práticas'],
  ['Tracao', 'Tração'],
  ['tracao', 'tração'],
  ['Variacoes', 'Variações'],
  ['variacoes', 'variações'],
  ['Varias', 'Várias'],
  ['varias', 'várias'],
  ['Visao', 'Visão'],
  ['visao', 'visão'],
  ['Historia', 'História'],
  ['historia', 'história'],
  ['Citaveis', 'Citáveis'],
  ['citaveis', 'citáveis'],
  ['Formatacao', 'Formatação'],
  ['formatacao', 'formatação'],
  ['Instrumentacao', 'Instrumentação'],
  ['instrumentacao', 'instrumentação'],
  ['Afirmacao', 'Afirmação'],
  ['afirmacao', 'afirmação'],
  ['Evidencia', 'Evidência'],
  ['evidencia', 'evidência'],
  ['Indexacao', 'Indexação'],
  ['indexacao', 'indexação'],
  ['Aderencia', 'Aderência'],
  ['aderencia', 'aderência'],
  ['Agencias', 'Agências'],
  ['agencias', 'agências'],
  ['Aproximacao', 'Aproximação'],
  ['aproximacao', 'aproximação'],
  ['Autorizacao', 'Autorização'],
  ['autorizacao', 'autorização'],
  ['Clinica', 'Clínica'],
  ['clinica', 'clínica'],
  ['Clinico', 'Clínico'],
  ['clinico', 'clínico'],
  ['Codigo', 'Código'],
  ['codigo', 'código'],
  ['Contabil', 'Contábil'],
  ['contabil', 'contábil'],
  ['Diagnosticos', 'Diagnósticos'],
  ['diagnosticos', 'diagnósticos'],
  ['Divergencia', 'Divergência'],
  ['divergencia', 'divergência'],
  ['Evolucao', 'Evolução'],
  ['evolucao', 'evolução'],
  ['Expansao', 'Expansão'],
  ['expansao', 'expansão'],
  ['Impressao', 'Impressão'],
  ['impressao', 'impressão'],
  ['Inflacao', 'Inflação'],
  ['inflacao', 'inflação'],
  ['Ja', 'Já'],
  ['ja', 'já'],
  ['Juridico', 'Jurídico'],
  ['juridico', 'jurídico'],
  ['Legitima', 'Legítima'],
  ['legitima', 'legítima'],
  ['Legitimo', 'Legítimo'],
  ['legitimo', 'legítimo'],
  ['Mudanca', 'Mudança'],
  ['mudanca', 'mudança'],
  ['Mudancas', 'Mudanças'],
  ['mudancas', 'mudanças'],
  ['Dominio', 'Domínio'],
  ['dominio', 'domínio'],
  ['Dominios', 'Domínios'],
  ['dominios', 'domínios'],
  ['Objecoes', 'Objeções'],
  ['objecoes', 'objeções'],
  ['Auditavel', 'Auditável'],
  ['auditavel', 'auditável'],
  ['Auditaveis', 'Auditáveis'],
  ['auditaveis', 'auditáveis'],
  ['Organica', 'Orgânica'],
  ['organica', 'orgânica'],
  ['Persistencia', 'Persistência'],
  ['persistencia', 'persistência'],
  ['Preco', 'Preço'],
  ['preco', 'preço'],
  ['Precos', 'Preços'],
  ['precos', 'preços'],
  ['Previo', 'Prévio'],
  ['previo', 'prévio'],
  ['Raciocinio', 'Raciocínio'],
  ['raciocinio', 'raciocínio'],
  ['Reaproveitavel', 'Reaproveitável'],
  ['reaproveitavel', 'reaproveitável'],
  ['Reaproveitaveis', 'Reaproveitáveis'],
  ['reaproveitaveis', 'reaproveitáveis'],
  ['Republicacao', 'Republicação'],
  ['republicacao', 'republicação'],
  ['Reproducao', 'Reprodução'],
  ['reproducao', 'reprodução'],
  ['Rastreavel', 'Rastreável'],
  ['rastreavel', 'rastreável'],
  ['Explicita', 'Explícita'],
  ['explicita', 'explícita'],
  ['Explicitas', 'Explícitas'],
  ['explicitas', 'explícitas'],
  ['Explicito', 'Explícito'],
  ['explicito', 'explícito'],
  ['Explicitos', 'Explícitos'],
  ['explicitos', 'explícitos'],
  ['Semanticas', 'Semânticas'],
  ['semanticas', 'semânticas'],
  ['Secundaria', 'Secundária'],
  ['secundaria', 'secundária'],
  ['Secundarias', 'Secundárias'],
  ['secundarias', 'secundárias'],
  ['Secundario', 'Secundário'],
  ['secundario', 'secundário'],
  ['Secundarios', 'Secundários'],
  ['secundarios', 'secundários'],
  ['Unica', 'Única'],
  ['unica', 'única'],
  ['Unicas', 'Únicas'],
  ['unicas', 'únicas'],
  ['Area', 'Área'],
  ['area', 'área'],
  ['Sao', 'São'],
  ['sao', 'são'],
  ['Previsivel', 'Previsível'],
  ['previsivel', 'previsível'],
  ['Nao', 'Não'],
  ['nao', 'não'],
  ['Fisica', 'Física'],
  ['fisica', 'física'],
  ['Fisico', 'Físico'],
  ['fisico', 'físico'],
  ['Renderizacao', 'Renderização'],
  ['renderizacao', 'renderização'],
  ['Trafego', 'Tráfego'],
  ['trafego', 'tráfego']
];

function escapeForRegex(value: string) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function shouldSkipString(key: string | undefined, value: string) {
  if (key && skipKeys.has(key)) {
    return true;
  }

  if (value.startsWith('/') || value.startsWith('http') || value.startsWith('#')) {
    return true;
  }

  if (!/\s/.test(value) && /[@/:._-]/.test(value)) {
    return true;
  }

  if (/^\d{4}-\d{2}-\d{2}/.test(value)) {
    return true;
  }

  return false;
}

export function normalizeEditorialText(value: string, key?: string) {
  if (shouldSkipString(key, value)) {
    return value;
  }

  return replacements.reduce((current, [from, to]) => {
    return current.replace(new RegExp(`\\b${escapeForRegex(from)}\\b`, 'g'), to);
  }, value);
}

export function normalizeEditorialValue<T>(value: T, key?: string): T {
  if (typeof value === 'string') {
    return normalizeEditorialText(value, key) as T;
  }

  if (Array.isArray(value)) {
    if (key && skipKeys.has(key)) {
      return value;
    }

    return value.map((item) => normalizeEditorialValue(item)) as T;
  }

  if (value && typeof value === 'object') {
    const entries = Object.entries(value as Record<string, unknown>).map(([entryKey, entryValue]) => [
      entryKey,
      normalizeEditorialValue(entryValue, entryKey)
    ]);

    return Object.fromEntries(entries) as T;
  }

  return value;
}
